export enum BookingStatus {
  PENDING_LANDLORD = 'PENDING_LANDLORD', // tenant gửi yêu cầu
  REJECTED = 'REJECTED', // landlord từ chối
  PENDING_SIGNATURE = 'PENDING_SIGNATURE', // landlord đồng ý, chờ tenant ký
  SIGNED = 'SIGNED', // đủ chữ ký
  AWAITING_DEPOSIT = 'AWAITING_DEPOSIT',
  DEPOSIT_FUNDED = 'DEPOSIT_FUNDED',
  AWAITING_FIRST_RENT = 'AWAITING_FIRST_RENT',
  READY_FOR_HANDOVER = 'READY_FOR_HANDOVER',
  ACTIVE = 'ACTIVE',
  SETTLEMENT_PENDING = 'SETTLEMENT_PENDING',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
}
