export enum BookingStatus {
  PENDING_LANDLORD = 'PENDING_LANDLORD', // tenant gửi yêu cầu
  REJECTED = 'REJECTED', // landlord từ chối
  PENDING_SIGNATURE = 'PENDING_SIGNATURE', // landlord đồng ý, chờ tenant ký
  AWAITING_DEPOSIT = 'AWAITING_DEPOSIT',
  ESCROW_FUNDED_T = 'ESCROW_FUNDED_T',
  ESCROW_FUNDED_L = 'ESCROW_FUNDED_L',
  DUAL_ESCROW_FUNDED = 'DUAL_ESCROW_FUNDED',
  READY_FOR_HANDOVER = 'READY_FOR_HANDOVER',
  ACTIVE = 'ACTIVE',
  SETTLEMENT_PENDING = 'SETTLEMENT_PENDING',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
}
