export enum NotificationTypeEnum {
  GENERAL = 'GENERAL',
  PAYMENT = 'PAYMENT',
  CONTRACT = 'CONTRACT',
  SYSTEM = 'SYSTEM',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  PAYMENT_OVERDUE = 'PAYMENT_OVERDUE',
  DEPOSIT_REMINDER = 'DEPOSIT_REMINDER',
  CONTRACT_REMINDER = 'CONTRACT_REMINDER',
  MAINTENANCE_REMINDER = 'MAINTENANCE_REMINDER',
}
